// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7xg3NPB8CumQqHDGNq1qDlORdWgHPZM',
    appId: '1:949826355624:web:309ffb6bc6757765c81d9d',
    messagingSenderId: '949826355624',
    projectId: 'addflutter-72e0c',
    authDomain: 'addflutter-72e0c.firebaseapp.com',
    storageBucket: 'addflutter-72e0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKlO7lhxySKt0drv4jiPAgfa-XO5XAyvE',
    appId: '1:949826355624:ios:79b371df42e39f36c81d9d',
    messagingSenderId: '949826355624',
    projectId: 'addflutter-72e0c',
    storageBucket: 'addflutter-72e0c.appspot.com',
    iosClientId: '949826355624-5cr89i9t4ithf8gv8aah05s3a0c8gcm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.addfluttertofirebase',
  );
}
